### ISSUE TITLE
Create Birthday class

### ISSUE THREAD

**Issue by bobantonbob** [VasylMartyniv/GoIT_Phone_Book_bot#4]
Гілка - feature/birthday

Поля:
date

Клас повиненн могти:
- [x] Валідувати дату при ініціалізації
- [x] Ініціалізовуватись із заданням дати
- [x] Перетворюватись в строку для виведення
- [x] Змінювати дату
- [x] Видаляти дату

**Comment by bobantonbob** [comment]
![Image](https://github.com/VasylMartyniv/GoIT_Phone_Book_bot/assets/130400459/48f636de-7621-40be-a238-17450a1091ae)
![Image](https://github.com/VasylMartyniv/GoIT_Phone_Book_bot/assets/130400459/30a80a66-0262-40aa-9aa9-68b738c207ce)
![Image](https://github.com/VasylMartyniv/GoIT_Phone_Book_bot/assets/130400459/2b6e3882-46f5-4d98-857a-895d29e347af)

**Comment by bobantonbob** [comment]
не бачив, а виходить ти вже шось наробив, соррі, код працює, запускав ??

**Comment by bobantonbob** [comment]
я зробив валідацію коректності, та не даю оновити у майбутньому та дату мінус 120 років

**Comment by bobantonbob** [comment]
реалізував пошук контактів на обрану кількість днів від поточної

**Comment by bobantonbob** [comment]
додав це:
   "delete_birthday": "Видалити день народження",  # додано видалити день народження зробити Null

бо його не було

**Comment by bobantonbob** [comment]
з моєї гілки мож запустити все працюї 

(venv) PS C:\Users\anton\PycharmProjects\Neoversity\GoIT_Phone_Book_bot\src> py main.py
Введіть команду:

**Comment by bobantonbob** [comment]
переробив народження  для Field, зразу не побачив його

**Comment by Vitalii1983-vr** [comment]
Дякую

Пт, 24 мая 2024 г. в 13:05, ANTON BABENKO ***@***.***>:

**Comment by bobantonbob** [comment]
![Image](https://github.com/VasylMartyniv/GoIT_Phone_Book_bot/assets/130400459/87b3743d-c797-4434-b381-00a77ba2c69c)



![Image](https://github.com/VasylMartyniv/GoIT_Phone_Book_bot/assets/130400459/eda17241-3efd-459b-bd4b-4bdc84a2a9c6)


додав метод для отримання запису за його ID для нотаток та народження шоб перехоплювати коли вводять число ід котрого немає у базі

**Comment by Vitalii1983-vr** [comment]
1/ # файл utils.py
Додав у файл utils.py функції для зміни та видалення дня народження

def change_birthday():
    name = input("Enter name: ")
    new_birthday = input("Enter new birthday (DD.MM.YYYY): ")
    print(change_birthday([name, new_birthday], book))

def delete_birthday():
    name = input("Enter name: ")
    print(delete_birthday([name], book))


2/ # файл comands.py
Додав до файлу comands.py команди 
1. "change_birthday": "Змінити день народження"
2. "delete_birthday": "Видалити день народження"
.
3/ # файл record.py
Додано новий клас Birthday для валідації та роботи з датою народження, оновлено клас Record

- Додано базовий клас Field для полів запису.
- Створено клас Birthday для зберігання та валідації дати народження.
- Оновлено клас Record:
  - Додано методи add_birthday, change_birthday та delete_birthday для роботи з датою народження.
  - Метод __str__ тепер коректно виводить дату народження у форматі 'DD.MM.YYYY'.

Ці зміни додають можливість валідувати, ініціалізовувати, змінювати та видаляти дату народження для кожного запису. Вони також полегшують роботу з датами народження у наших контактах.

У цьому оновленні ми додали новий клас Birthday для роботи з датами народження. Це дозволяє валідувати дату при ініціалізації, перетворювати її в строку для виведення, змінювати та видаляти дату.

Ми також оновили клас Record, щоб інтегрувати новий клас Birthday. Тепер ви можете додавати, змінювати та видаляти дату народження для кожного запису.

Будь ласка, перегляньте ці зміни та перевірте їх у вашому середовищі розробки.

**Comment by bobantonbob** [comment]
а як ти це перевірив ?
<img width="426" alt="image" src="https://github.com/VasylMartyniv/GoIT_Phone_Book_bot/assets/130400459/4bbbbc74-ecf9-45db-a949-9f7316bd11c4">
